### ISSUE TITLE
What if there is navigationBar present?

### ISSUE THREAD

**Issue by kyco16** [bryankeller/BLKFlexibleHeightBar#5]
I have a UIViewController inside a `UINavigationController` as well as `UITabBarController`. I have 2 `UIViews`, one being the month name and the other being a weekly view. I obviously have a `navBar` that contains 3 `UIBarButtonItems`. How would I go about configuring this flexible height bar to work with the `navBar` and my two `UIViews`, which are all set in the storyboard?

**Comment by bryankeller** [comment]
On the view controller that you want to use this, you'd have hide the built in navigation bar and programmatically add a BLKFlexibleHeightBar. 

If you absolutely need the built in navigation bar with bar button items (rather than a BLKFlexibleHeightBar with subviews), then this solution might not be the best one for your needs.
