### ISSUE TITLE
proxy object

### ISSUE THREAD

**Issue by ajkiosd** [bryankeller/BLKFlexibleHeightBar#6]
hi
first thanks for your great work.
i have problem when use UITebleView and want to use my scrollViewDelegate.
i suggest to implement like this control:

https://github.com/ninjinkun/NJKScrollFullScreen

    _scrollProxy = [[NJKScrollFullScreen alloc] initWithForwardTarget:self]; // UIScrollViewDelegate and UITableViewDelegate methods proxy to ViewController
    // and in NJKScrollFullScreen Class

    - (void)scrollViewDidScroll:(UIScrollView *)scrollView
    {
        if ([_forwardTarget respondsToSelector:@selector(scrollViewDidScroll:)]) {
            [_forwardTarget scrollViewDidScroll:scrollView];
        }
        ........
    }

**Comment by bryankeller** [comment]
Hi @ajkiosd,

I'm not exactly sure what issue you're having. Are you having trouble using BLKFlexibleHeightBar since it uses the UITableView's delegate? 

If this is the case, have a look at BLKDelegateSplitter. It will let you user your view controller as one UITableViewDelegate and BLKFlexibleHeightBar as the other.

**Comment by ajkiosd** [comment]
yes it was my problem.
now i see BLKDelegateSplitter.
i apologize for that. :)
thanks

**Comment by bryankeller** [comment]
Glad that helped =)
